import type { AgentInsight, MarketNews, StockProfile } from "../types/landing.types";

export const stockProfiles: StockProfile[] = [
  {
    symbol: "2330",
    name: "台積電",
    industry: "半導體製造",
    business: "全球先進製程晶圓代工龍頭，核心收入來自高效能運算、智慧手機與 AI 相關需求。",
    price: 875,
    changePercent: 1.42,
    marketCap: "22.7 兆",
    revenue: "月營收年增 34%",
    riskLevel: "medium",
    agentStatus: "已完成分析",
    thesis: "先進製程需求仍是主要成長引擎，短線估值與匯率波動需要納入風險控管。",
    highlights: ["AI 伺服器需求", "3nm 產能利用率", "海外擴廠成本"],
    trend: "up",
    sparkline: [38, 42, 41, 46, 51, 55, 61, 59, 66, 72],
  },
  {
    symbol: "2454",
    name: "聯發科",
    industry: "IC 設計",
    business: "聚焦手機晶片、智慧裝置、車用與連網晶片，受消費電子週期與高階產品組合影響。",
    price: 1210,
    changePercent: -0.58,
    marketCap: "1.9 兆",
    revenue: "季度毛利率改善",
    riskLevel: "medium",
    agentStatus: "等待新聞更新",
    thesis: "產品組合升級支撐中期表現，但手機需求復甦速度仍是主要不確定性。",
    highlights: ["旗艦手機晶片", "邊緣 AI 裝置", "庫存週期"],
    trend: "flat",
    sparkline: [58, 60, 57, 56, 59, 61, 60, 62, 61, 63],
  },
  {
    symbol: "2308",
    name: "台達電",
    industry: "電源與能源管理",
    business: "提供電源管理、散熱、工業自動化與資料中心能源解決方案。",
    price: 393,
    changePercent: 2.18,
    marketCap: "1.0 兆",
    revenue: "資料中心動能升溫",
    riskLevel: "low",
    agentStatus: "已完成分析",
    thesis: "資料中心電源與節能需求提升，提供較穩定的長期成長敘事。",
    highlights: ["資料中心電源", "工業自動化", "能源效率"],
    trend: "up",
    sparkline: [45, 47, 48, 50, 53, 52, 56, 60, 64, 68],
  },
  {
    symbol: "2317",
    name: "鴻海",
    industry: "電子製造服務",
    business: "全球 EMS 大廠，布局消費電子、伺服器、電動車與雲端基礎建設。",
    price: 168,
    changePercent: 0.31,
    marketCap: "2.3 兆",
    revenue: "AI 伺服器占比提高",
    riskLevel: "medium",
    agentStatus: "資料整理中",
    thesis: "AI 伺服器成長提高評價想像，但低毛利結構仍限制獲利彈性。",
    highlights: ["AI 伺服器", "電動車平台", "營益率改善"],
    trend: "flat",
    sparkline: [50, 52, 49, 51, 52, 54, 53, 55, 54, 56],
  },
];

export const marketNews: MarketNews[] = [
  {
    id: "news-1",
    company: "台積電",
    category: "產業需求",
    date: "2026-05-19",
    title: "AI 晶片需求延續，先進製程能見度維持高檔",
    summary: "市場關注高效能運算訂單與海外擴廠成本，短線評價仍受資本支出節奏影響。",
  },
  {
    id: "news-2",
    company: "聯發科",
    category: "產品週期",
    date: "2026-05-18",
    title: "高階手機平台競爭升溫，法人觀察毛利率修復速度",
    summary: "新平台放量有助產品組合改善，但終端需求復甦仍需追蹤通路庫存變化。",
  },
  {
    id: "news-3",
    company: "台達電",
    category: "資料中心",
    date: "2026-05-17",
    title: "資料中心電源與散熱題材延續，能源效率成關鍵敘事",
    summary: "AI 機房建置帶動高效率電源需求，市場同步評估產能配置與訂單持續性。",
  },
];

export const agentInsights: AgentInsight[] = [
  {
    title: "技術面",
    label: "趨勢",
    description: "比較價格區間、量能變化與短中期趨勢，避免只看單日漲跌。",
  },
  {
    title: "風險評估",
    label: "控管",
    description: "標記估值、波動、流動性與資料不足風險，協助設定觀察條件。",
  },
  {
    title: "發展方向",
    label: "情境",
    description: "以短中長期情境拆解企業成長邏輯與可能的反向風險。",
  },
  {
    title: "投資建議",
    label: "分級",
    description: "依保守、中性、積極風險承受度輸出不同觀察建議，不做絕對指令。",
  },
];
